CREATE DATABASE EXERCICIO;

USE EXERCICIO;

CREATE TABLE FUNCIONARIO(
    idFuncionario INTEGER,
    nome VARCHAR(100),
    email VARCHAR(200),
    sexo VARCHAR(10),
    departamento varchar(100),
    admissão varchar(10),
    salario FLOAT,
    cargo VARCHAR(100),
    idRegiao int
);

/* tRAGA OS FUNCIONÁRIOS QUE TRABALHEM NO DEPARTAMENTO DE FILMES OU DE ROUPAS */

SELECT NOME, EMAIL, DEPARTAMENTO FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'ROUPAS' OR DEPARTAMENTO = 'FILMES';

SELECT COUNT(*), DEPARTAMENTO FROM FUNCIONARIOS GROUP BY DEPARTAMENTO;

SELECT NOME, EMAIL, DEPARTAMENTO FROM FUNCIONARIOS WHERE (DEPARTAMENTO = 'LAR' OR DEPARTAMENTO = 'FILMES') AND SEXO = 'FEMININO';

SELECT * FROM FUNCIONARIOS WHERE (DEPARTAMENTO = LAR AND SEXO = 'FEMININO') OR (DEPARTAMENTO = 'FILMES' AND SEXO = 'FEMININO') -- BETTLE

SELECT NOME, SEXO, DEPARTAMENTO FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'MASCULINO' OR SEXO = 'JARDIN' GROUP BY DEPARTAMENTO;

SELECT COUNT(*) FROM FUNCIONARIOS;