CREATE DATABASE OFICINA;

USE OFICINA;

CREATE TABLE CLIENTES(
    IDCLIENTE INT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('FAM', 'MAL' ) NOT NULL,
    ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONES(
    IDTELEFONE INT ,
    TIPO ENUM('CEL', 'RES', 'EMP'),
    NUMERO VARCHAR(14),
    ID_CLIENTE INT
);

CREATE TABLE MARCAS(
    IDMARCA INT,
    NOME_MARCA VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE CARROS(
    IDCARRO INT,
    PLACA CHAR(7) NOT NULL UNIQUE,
    MODELO VARCHAR(30) NOT NULL,
    ID_MARCA INT
);

CREATE TABLE CORES(
    IDCOR INT,
    NOME_COR VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE CARRO_COR(
    ID_CARRO INT,
    ID_COR INT,
    PRIMARY KEY(ID_CARRO,ID_COR)
);


ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES
PRIMARY KEY(IDCLIENTE);

ALTER TABLE CLIENTES MODIFY IDCLIENTE INT AUTO_INCREMENT;

ALTER TABLE CARROS ADD CONSTRAINT PK_CARROS
PRIMARY KEY(IDCARRO);

ALTER TABLE CARROS MODIFY IDCARRO INT AUTO_INCREMENT;

ALTER TABLE CLIENTES ADD CONSTRAINT FK_CARROS_CLIENTES
FOREIGN KEY(ID_CARRO) REFERENCES CARROS(IDCARRO); 

ALTER TABLE TELEFONES ADD CONSTRAINT PK_TELEFONES
PRIMARY KEY(IDTELEFONE);

ALTER TABLE TELEFONES MODIFY IDTELEFONE INT AUTO_INCREMENT;

ALTER TABLE TELEFONES ADD CONSTRAINT FK_CLIENTES_TELEFNES
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(IDCLIENTE);

ALTER TABLE MARCAS ADD CONSTRAINT PK_MARCAS
PRIMARY KEY(IDMARCA);

ALTER TABLE MARCAS MODIFY IDMARCA INT AUTO_INCREMENT;

ALTER TABLE CARROS ADD CONSTRAINT FK_MARCAS_CARROS
FOREIGN KEY(ID_MARCA) REFERENCES MARCAS(IDMARCA);

ALTER TABLE CORES ADD CONSTRAINT PK_CORES
PRIMARY KEY(IDCOR);

ALTER TABLE CORES MODIFY IDCOR INT AUTO_INCREMENT;

ALTER TABLE CARRO_COR ADD CONSTRAINT PK_CARRO_COR
PRIMARY KEY(ID_CARRO,ID_COR);

ALTER TABLE CARRO_COR ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR) REFERENCES CORES(IDCOR);

ALTER TABLE CARRO_COR ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO) REFERENCES CARROS(IDCARRO);

INSERT INTO CARROS VALUES(NULL, 'A2309AS', 'UNO', NULL);
INSERT INTO CARROS VALUES(NULL, 'B2309AS', 'PALIO', NULL);
INSERT INTO CARROS VALUES(NULL, 'C2309AS', 'CELTA', NULL);
INSERT INTO CARROS VALUES(NULL, 'D2309AS', 'FK', NULL);
INSERT INTO CARROS VALUES(NULL, 'E2309AS', 'RENO', NULL);
INSERT INTO CARROS VALUES(NULL, 'F2309AS', 'DUST', NULL);
INSERT INTO CARROS VALUES(NULL, 'G2309AS', 'FIESTA', NULL);
INSERT INTO CARROS VALUES(NULL, 'H2309AS', 'CIVIC', NULL);
INSERT INTO CARROS VALUES(NULL, 'I2309AS', 'FIT', NULL);
INSERT INTO CARROS VALUES(NULL, 'J2309AS', 'COROLA', NULL);

INSERT INTO MARCAS VALUES(NULL, 'FIAT');
INSERT INTO MARCAS VALUES(NULL, 'HONDA');
INSERT INTO MARCAS VALUES(NULL, 'FORD');
INSERT INTO MARCAS VALUES(NULL, 'RENAULT');
INSERT INTO MARCAS VALUES(NULL, 'TOYOTA');
INSERT INTO MARCAS VALUES(NULL, 'CHEVROLET');


INSERT INTO CORES VALUES(NULL, "AZUL");
INSERT INTO CORES VALUES(NULL, "VERMELHO");
INSERT INTO CORES VALUES(NULL, "VERDE");
INSERT INTO CORES VALUES(NULL, "AMARENO");
INSERT INTO CORES VALUES(NULL, "PRATA");
INSERT INTO CORES VALUES(NULL, "PRETO");
INSERT INTO CORES VALUES(NULL, "BRANCO");

INSERT INTO CARRO_COR VALUES(1,4);
INSERT INTO CARRO_COR VALUES(10,1);
INSERT INTO CARRO_COR VALUES(16,7);
INSERT INTO CARRO_COR VALUES(17,7);
INSERT INTO CARRO_COR VALUES(17,1);
INSERT INTO CARRO_COR VALUES(12,5);
INSERT INTO CARRO_COR VALUES(15,6);
INSERT INTO CARRO_COR VALUES(13,3);
INSERT INTO CARRO_COR VALUES(14,2);
INSERT INTO CARRO_COR VALUES(18,2);
INSERT INTO CARRO_COR VALUES(11,4);
INSERT INTO CARRO_COR VALUES(11,7);

INSERT INTO CLIENTES VALUES(NULL, 'JOÃO', 'MAL', 1);
INSERT INTO CLIENTES VALUES(NULL, 'MIGUEL', 'MAL', 10);
INSERT INTO CLIENTES VALUES(NULL, 'ANA', 'FAM', 11);
INSERT INTO CLIENTES VALUES(NULL, 'LUANA', 'FAM', 12);
INSERT INTO CLIENTES VALUES(NULL, 'JORGE', 'MAL', 13);
INSERT INTO CLIENTES VALUES(NULL, 'JORGE', 'MAL', 14);
INSERT INTO CLIENTES VALUES(NULL, 'EMANUEL', 'MAL', 15);
INSERT INTO CLIENTES VALUES(NULL, 'VICTOR', 'MAL', 16);
INSERT INTO CLIENTES VALUES(NULL, 'GABRIELA', 'FAM', 17);
INSERT INTO CLIENTES VALUES(NULL, 'JOAQUINA', 'FAM', 18);

INSERT INTO TELEFONES(IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL, 'CEL', '3123456709', 1);
INSERT INTO TELEFONES(IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL, 'RES', '6567567583', 1);
INSERT INTO TELEFONES(IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL, 'EMP', '323423234', 2);
INSERT INTO TELEFONES(IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL, 'CEL', '3244543453', 3);
INSERT INTO TELEFONES(IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL, 'RES', '43457980', 4);
INSERT INTO TELEFONES(IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL, 'CEL', '00986765344', 5);
INSERT INTO TELEFONES(IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL, 'RES', '1235890967', 5);
INSERT INTO TELEFONES(IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL, 'EMP', '456789012', 5);
INSERT INTO TELEFONES(IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL, 'RES', '21234456', 10);
INSERT INTO TELEFONES(IDTELEFONE, TIPO, NUMERO, ID_CLIENTE) VALUES(NULL, 'CEL', '98764543535', 7);

UPDATE CARROS SET ID_MARCA = '1' WHERE PLACA IN('A2309AS', 'B2309AS');
UPDATE CARROS SET ID_MARCA = '3' WHERE PLACA IN('D2309AS', 'G2309AS');
UPDATE CARROS SET ID_MARCA = '2' WHERE PLACA IN('H2309AS', 'I2309AS');
UPDATE CARROS SET ID_MARCA = '4' WHERE PLACA IN('E2309AS', 'F2309AS');
UPDATE CARROS SET ID_MARCA = '5' WHERE PLACA = 'J2309AS';
UPDATE CARROS SET ID_MARCA = '6' WHERE PLACA = 'C2309AS';