DELIMITER $ /* STORED PROCEDURES */

CREATE PROCEDURE NOME() BEGIN QUALQUER PROGRAÇÃO END $

CREATE PROCEDURE NOME_EMPRESA() BEGIN
SELECT  'UNIVERSIDADE DOS DADOS' AS EMPRESA; END $
 /* CHAMANDO UMA PROCEDURE */

CALL NOME_EMPRESA()$ DELIMITER; CALL NOME_EMPRESA();
  
/* PRCEDURE COM PARAMETRO */ 

DELIMITER $

CREATE PROCEDURE CONTA() BEGIN
SELECT  10 + 10 AS CONTA; END $ DELIMITER; CALL CONTA();

DROP PROCEDURE CONTA(); DELIMITER $
CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT) BEGIN
SELECT  NUMERO1 + NUMERO2 AS CONTA; END $ DELIMITER; CALL CONTA(100,500);

SELECT * FROM ALUNOS


CREATE TABLE CURSO(
    IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    HORAS INT(3) NOT NULL,
    VALOR FLOAT(10,2) NOT NULL
);

INSERT INTO CURSO VALUES(NULL, 'JAVA', 30, 500.00);
INSERT INTO CURSO VALUES(NULL, 'FUNDAMENTOS DE BANCO DE DADOS', 40, 700.00);

DELIMITER #

CREATE PROCEDURE CAD_CURSO(
    P_CURSO VARCHAR(30),
    P_HORAS INT(3),
    P_VALOR FLOAT(10,2)
)
BEGIN
    INSERT INTO CURSO VALUES(NULL, P_CURSO, P_HORAS, P_VALOR);
END
#

CALL CAD_CURSO('BI SQL SERVER', 35, 3000.00);
CALL CAD_CURSO('POWER BI', 20, 1000.00);
CALL CAD_CURSO('TABLEAU', 30, 1200.00);

/* PRCEDURE PARA CONSULTAR CURSOS */

CREATE PROCEDURE SEARCH_CRUSO(P_CURSO VARCHAR(30))
BEGIN
    SELECT NOME, HORAS, VALOR FROM CURSO WHERE NOME LIKE CONCAT('%',P_CURSO,'%') ;
END
#