CREATE TABLE TABELA(
    COLUNA1 VARCHAR(30),
    COLUNA2 VARCHAR(30),
    COLUNA3 VARCHAR(30)
);


ALTER TABLE TABELA ADD PRIMARY KEY(COLUNA1);
ALTER TABLE TABELA ADD COLUNA VARCHAR(30);
ALTER TABLE TABELA ADD COLUNA100 INT;
ALTER TABLE TABELA ADD COLUMN COLUNA4 VARCHAR(30) NOT NULL UNIQUE AFTER COLUNA3;


/* PARA ALTERAR O TIPO DE UMA COLUNA, OS DADOS QUE ESTÃO NA COLUNA DEVEM SER COMPATIVES COM O DADO DA COLUA */

ALTER TABLE TABELA MODIFY COLUNA2 DATE NOT NULL;

ALTER TABLE TABELA CHANGE COLUNA100 COLUNA200;

/* RENOMEANDO O NOME DA TABELA */

ALTER TABLE TABELA RENAME PESSOA;

CREATE TABLE TIME(
       IDTIME INT PRIMARY KEY AUTO_INCREMENT,
       TIME VARCHAR(30),
       ID_PESSOA VARCHAR(30)
);

ALTER TABLE TIME ADD FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(COLUNA1);

ALTER TABLE PESSOA MODIFY COLUNA1 INT;

/* VERIFICAR AS CHAVES */

SHOW CREATE TABLE TIME;

/* ORCANIZAÇÃO DE CHAVES = CONSTRAINT = (REGRA) */
/* A CHAVE PRIMÁRIA É UMA REGRA DE INTEGRIDADE REFERENCIAL

    PRMARY KEY = GARANTE QUE NOSSO REGISTRO SEJA UNICO É NÃO SE REPITA
    FOREIGN KEY = GARANTE QUE NÃO TENHA RESIGISTRO EM UMA TABELA SEM REFERÊNCIA EM OUTRA TABLEA. 
 */

CREATE TABLE JOGADOR(
    IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30)

 );

CREATE TABLE TIMES(
    IDTIME INT PRIMARY KEY AUTO_INCREMENT,
    NOMETIME VARCHAR(30),
    ID_JOGADOR INT,
    FOREIGN KEY(ID_JOGADOR) REFERENCES JOGADOR(IDJOGADOR)
 );

INSERT INTO JOGADOR VALUES(NULL, 'GERREIRO');
INSERT INTO TIMES VALUES(NULL, 'FLAMENTO', 1);

SHOW CREATE TABLE JOGADOR;
SHOW CREATE TABLE TIMES;

/* AÇÕES DE CONTRAINT */

USE COMERCIO;

DROP TABLE ENDERECO;
DROP TABLE TELEFONE;
DROP TABLE CLIENTE;

CREATE TABLE CLIENTE(
    IDCLIENTE INT,
    NOME VARCHAR(30) NOT NULL
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT,
    TIPO CHAR(3) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    ID_CLIENTE INT
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY(IDCLIENTE);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

SHOW DATABASES;
USE INFORMATION_SCHEMA;

SHOW TABLES;

DESC TABLE_CONSTRAINTS;

SELECT CONSTRAINT_SCHEMA AS "BANCO",
       TABLE_NAME AS 'TABELA',
       CONSTRAINT_NAME AS 'NOME',
       CONSTRAINT_TYPE AS 'TIPO'
       FROM TABLE_CONSTRAINTS
       WHERE CONSTRAINT_SCHEMA = 'COMERCIO';

/* APAGANDO CONSTRAINT */

ALTER TABLE TELEFONE
DROP FOREIGN KEY FK_CLIENTE_TELEFONE

use comercio;
