/* SELEÇÃO, PORJEÇÃO E JUNÇÃO */ /* PROJEÇÃO - > É TUDO QUE VOCÊ VER NA TELA*/
SELECT  NOW() AS DATA_ATUAL;

SELECT  2+2 AS SOMA;

SELECT  2 + 2 AS SOMA
       ,NOME
       ,NOW()
FROM CLIENTE;

SELECT  NOME
       ,SEXO
       ,TIPO
       ,TELEFONE
       ,BAIRRO;
 /* SELEÇÃO - > É UM SUB CONJUNTO FORMADO APARTIR DO CONJUNTO TOTAL DE ELEMENTOS A CLAUSULA DE CELEÇÃO É O
WHERE */
SELECT  NOME
       ,SEXO
       ,EMAIL /* PROJEÇÃO */
FROM CLIENTE /* ORIGEM */
WHERE SEXO = 'F'; 

/*SELEÇÃO*/ /* OBS: SEPRE QUE REALIZAMOS UMA PROJETÇAO TE UMA TABELA PECISAMOS SABER A ORIGEM, CASO NÃO TENHA A ORIGEM AS PORJEÇÕES SÃO PROGRAMADAS OU FUNÇÕES */

SELECT  NUMERO
FROM TELEFONE
WHERE TIPO = 'CEL'

/* Junção */

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE;

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE
AND SEXO = 'F';

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE;

SELECT NOME, SEXO, BAIRRO, CIDADE /* PROJEÇÃO */
FROM CLIENTE /* ORIGEM*/
INNER JOIN ENDERECO /* JUNÇÃO */
ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F'; /* SELEÇÃO */

SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE 
INNER JOIN TELEFONE
ON IDCLIENTE = ID_CLIENTE;

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE;

/*
       Categorias da linguagem SQL
DML -> DATA MANIPULATION LANGUAGE
DDL -> DATA DEFINITION LANGUAGE
DCL -> DATA CONTROL LANGUAGE
TCL -> TRANSACTION CONTROL LANGUAGE

*/

/* DML - INSERT*/

INSERT INTO CLIENTE VALUES(NULL, 'PAULA', 'M', NULL, '2345456781');
INSERT INTO ENDERECO VALUES(NULL, 'RUA JOAQUIM SILVA', 'ALVORADA', 'NITEROI', 'RJ', 12);

SELECT * FROM CLIENTE;

/* MANIPULATION TO FILTER */

SELECT * FROM CLIENTE WHERE SEXO = 'M';

/* UPDATE */

SELECT * FROM CLIENTE WHERE IDCLIENTE = 12;
UPDATE CLIENTE SET SEXO = 'F' WHERE IDCLIENTE = 12;

/* DELETE */

INSERT INTO CLIENTE VALUES(NULL, 'XXX', 'M', NULL, 'XXX');
SELECT * FROM CLIENTE WHERE IDCLIENTE = 13; 

DELETE FROM CLIENTE WHERE IDCLIENTE = 13;

/* DDL - DATA DEFINITION LANGUAGE */
-- CREATE TABLE

CREATE TABLE PRODUTO(
       IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
       NOME_PRODUTO VARCHAR(30) NOT NULL,
       PRECO INT,
       FRETE FLOAT(10,2) NOT NULL
);

-- ALTER TABLE

/* ALTERANDO U NOME DE UMA COLUNA - CHANGE */
ALTER TABLE PRODUTO
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

-- MODIFY ALTERADNO TIPO

ALTER TABLE PRODUTO
MODIFY VALOR_UNITARIO VARCHAR(50);

-- ADICIONANDO COLUNA

ALTER TABLE PRODUTO
ADD PESO FLOAT(10,2) NOT NULL;

-- APAGADNO UMA COLUNA 

ALTER TABLE PRODUTO
DROP COLUMN PESO;

-- COLOCANDO UMA COLUNA NÁ POSIÇÃO QUE DESEJA NA TABELA. 

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
FIRST;



