CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	HORAS INT,
	VALOR FLOAT(10,2),
	ID_PERREQ INT
);

ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQ
FOREIGN KEY(ID_PERREQ) REFERENCES CURSOS(IDCURSO);

INSERT INTO CURSOS VALUES(NULL, 'BD RELACIONAL', 20, 400.00, NULL);
INSERT INTO CURSOS VALUES(NULL, 'BUISNESS INTELIGENCE', 40, 800.00, 1);
INSERT INTO CURSOS VALUES(NULL, 'RELATORIOS AVANCADOS', 30, 600.00, 2);
INSERT INTO CURSOS VALUES(NULL, 'LOGICA PROGRAM', 20, 400.00, NULL);
INSERT INTO CURSOS VALUES(NULL, 'RUBY', 30, 500.00, 4);

SELECT NOME, HORAS, VALOR, IFNULL(ID_PERREQ, 'SEM REQUISITO') REQUISITO
FROM CURSOS;

SELECT C.NOME, C.HORAS, C.VALOR, IFNULL(P.NOME, 'SEM REQUISITO')  AS 'NOME_REQUISITO'
FROM CURSOS C
LEFT JOIN CURSOS P ON P.IDCURSO = C.ID_PERREQ;