CREATE TABLE VENDEDORES(
    IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    SEXO CHAR(1),
    JANEIRO FLOAT(10,2),
    FEVEREIRO FLOAT(10,2),
    MARCO FLOAT(10,2)
);

INSERT INTO VENDEDORES VALUES(NULL, 'CARLOS', 'M', 123.23,32435.33,5645.45);
INSERT INTO VENDEDORES VALUES(NULL, 'MARIA', 'F', 1234.23,76865.33,5645.45);
INSERT INTO VENDEDORES VALUES(NULL, 'ANTONIO', 'M', 5646.23,768.33,5645.45);
INSERT INTO VENDEDORES VALUES(NULL, 'CLARA', 'F', 8678.23,78655.33,5645.45);
INSERT INTO VENDEDORES VALUES(NULL, 'ANDERSON', 'M', 98897.23,178232.33,5645.45);
INSERT INTO VENDEDORES VALUES(NULL, 'IVONE', 'F', 97823.23,1232.33,5645.45);
INSERT INTO VENDEDORES VALUES(NULL, 'JOÃO', 'M', 16575.23,87789.33,5645.45);
INSERT INTO VENDEDORES VALUES(NULL, 'JAMES', 'M', 897.23,1232.33,5645.45);

/* MAS - TRAZ O VALOR MAXIMO DE UMA COLUNA */

SELECT MAX(FEVEREIRO) AS MAIOR_FEV FROM VENDEDORES;

/* MIN - TRAZ O VALOR MINIMO DE UMA COLUNA */
SELECT MIN(FEVEREIRO) AS MAIOR_FEV FROM VENDEDORES;

/* AVG - TRAZ O VALOR MEDIO DE UMA COLUNA */
SELECT AVG(FEVEREIRO) AS MAIOR_FEV FROM VENDEDORES;

/* VARIAS FUNÇOES */
SELECT MAX(JANEIRO) AS MAX_JAN,
MIN(JANEIRO) AS MIN_JAN,
AVG(JANEIRO) AS MEDIA_JAN
FROM VENDEDORES;

/* TRUNCATE */

SELECT MAX(JANEIRO) AS MAX_JAN,
MIN(JANEIRO) AS MIN_JAN,
TRUNCATE(AVG(JANEIRO),2) AS MEDIA_JAN
FROM VENDEDORES;

/* AGREGADNO COM SUM () */

SELECT SUM(JANEIRO) AS TOTAL_JAN
FROM VENDEDORES;

/* VENDAS POR SEXO */

SELECT SEXO, SUM(MARCO) AS TOTAL_MARCO
FROM VENDEDORES
GROUP BY SEXO;

/* SUBQUERIES VENDEDOR QUE VENDEU MENOS EM MARCO E O SEU NOME */

UPDATE VENDEDORES SET MARCO = 100345.45 WHERE IDVENDEDOR = 2;

SELECT NOME, MIN(MARCO) AS MENOR_VALOR FROM VENDEDORES;
SELECT NOME, MAX(MARCO) AS MENOR_VALOR FROM VENDEDORES;

SELECT NOME, MARCO FROM VENDEDORES WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);

SELECT NOME, MARCO FROM VENDEDORES WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

SELECT NOME, MARCO 
FROM VENDEDORES 
WHERE MARCO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);

/* LINHAS */

SELECT NOME, JANEIRO, FEVEREIRO, MARCO,
(JANEIRO+FEVEREIRO+MARCO) AS 'TOTAL',
TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3, 2) AS 'MEDIA'
FROM VENDEDORES; 

SELECT NOME, JANEIRO, FEVEREIRO, MARCO,
(JANEIRO+FEVEREIRO+MARCO) AS 'TOTAL',
(JANEIRO+FEVEREIRO+MARCO) * .25 AS 'DESCONTO',
TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3, 2) AS 'MEDIA'
FROM VENDEDORES; 


