/*
       Categorias da linguagem SQL
DML -> DATA MANIPULATION LANGUAGE
DDL -> DATA DEFINITION LANGUAGE
DCL -> DATA CONTROL LANGUAGE
TCL -> TRANSACTION CONTROL LANGUAGE

*/

/* RELATÓRIO DE TODOS OS CLIENTE */

SELECT C.NOME, C.CPF, C.SEXO, C.EMAIL,
       T.TIPO, T.NUMERO,
       E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO 
FROM CLIENTE C
INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE;

/* RELATÓRIO DE HOMENS */

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE WHERE SEXO = 'M';

SELECT C.IDCLIENTE, C.NOME, C.CPF, C.SEXO, C.EMAIL,
       T.TIPO, T.NUMERO,
       E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO 
FROM CLIENTE C
INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';

SELECT * FROM CLIENTE WHERE IDCLIENTE IN(4, 5, 6,  11);

UPDATE CLIENTE SET SEXO = 'F' WHERE IDCLIENTE IN(4, 5, 6,  11);

/* RELATÓRIO DE MULHERES */

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE WHERE SEXO = 'F';

SELECT C.IDCLIENTE, C.NOME, C.CPF, C.SEXO, C.EMAIL,
       T.TIPO, T.NUMERO,
       E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO 
FROM CLIENTE C
INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F';

SELECT * FROM CLIENTE WHERE IDCLIENTE = 8;

UPDATE CLIENTE SET SEXO = 'M' WHERE IDCLIENTE = 8;

/* QUANTIDADE DE HOMENS E MULHERES */

SELECT COUNT(*) AS 'QUANTIDADE', SEXO FROM CLIENTE GROUP BY SEXO;
SELECT COUNT(*) AS 'QUANTIDADE_DE_MULHERES' FROM CLIENTE WHERE SEXO = 'F';

/* IDS E EMAIL DE MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E NÃO TENHAM CELULARES */

SELECT C.IDCLIENTE, C.EMAIL, C.NOME, C.SEXO, T.TIPO, E.BAIRRO, E.CIDADE
FROM CLIENTE C
INNER JOIN ENDERECO E ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T ON C.IDCLIENTE = T.ID_CLIENTE
WHERE T.TIPO <> 'CEL' AND C.SEXO = 'F' AND E.CIDADE = 'RIO DE JANEIRO' AND E.BAIRRO = 'CENTRO'; 


/*
PARA UMA CAMPANHA DE MARKETING, O SETOR SOLOCITOU UM 
RELATÓRIO COM NOME, EMAIL E TELEFONE CELULAR
DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO
VOCÊ TERA QUE PASSAR A QUERY PARA GERAR O RELATÓRIO PARA 
O PROGRAMADOR
*/

SELECT C.NOME, C.EMAIL, C.SEXO, T.NUMERO AS CELULAR
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE T.TIPO = 'CEL' AND E.ESTADO = 'RJ';

/*
PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SLICITOU UM
RELATÓRIO COM NOME, EMAIL E TELEFONE CELULAR
DAS MULHERES QUE MORAM NO ESTADO DE SÃO pAULO
VOCÊ TERA QUE PASSAR A QUERY PARA GERAR O RELATÓRIO PARA 
O PROGRAMADOR
*/

SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR, E.ESTADO, C.SEXO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE E.ESTADO = 'SP' AND T.TIPO = 'CEL' AND C.SEXO = 'F';

