SHOW DATABASES;

USE PROJECTO;

SELECT * FROM CLIENTE;

/* OR */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';

/* AND */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F' AND ENDERECO LIKE '%ESTACIO';

/* COUNT */

SELECT COUNT(*) AS 'QUANTIDADE DE REGISTROS DA TAB. CLIENTE' FROM CLIENTE;

/* GROUP BY */

SELECT SEXO, COUNT(*) FROM CLIENTE GROUP BY SEXO;
